# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classs', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
