# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='user_id',
            new_name='user',
        ),
    ]
